[theme]
primaryColor = "#00ff6a"
backgroundColor = "#08080e"
secondaryBackgroundColor = "#0e0e16"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
